[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
description = "A zero-copy DWARF debugging format parser."
documentation = "http://gimli-rs.github.io/gimli/gimli/index.html"
keywords = ["DWARF", "debug", "elf"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/gimli-rs/gimli"
version = "0.10.0"

[dependencies]
arrayvec = "0.3.20"
byteorder = "0.5.3"
fallible-iterator = "0.1.2"
leb128 = "0.2.1"

[dev-dependencies]
getopts = "0.2"
memmap = "0.4.0"
object = "0.1.0"
test-assembler = "0.1.3"

[features]
nightly = []
