[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
categories = ["development-tools::debugging", "development-tools::profiling", "parser-implementations"]
description = "A blazing fast DWARF debugging format parser."
documentation = "https://docs.rs/gimli"
keywords = ["DWARF", "debug", "ELF", "eh_frame"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/gimli-rs/gimli"
version = "0.15.0"

[badges]
travis-ci = { repository = "gimli-rs/gimli" }
coveralls = { repository = "gimli-rs/gimli" }

[dependencies]
arrayvec = { version = "0.4.6", default-features = false }
byteorder = { version = "1.0", default-features = false }
fallible-iterator = { version = "0.1.4", default-features = false }

[dev-dependencies]
getopts = "0.2"
memmap = "0.6"
object = "0.6"
test-assembler = "0.1.3"

[features]
std = ["fallible-iterator/std"]
nightly = ["fallible-iterator/alloc"]
default = ["std"]
