[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>", "Philip Craig <philipjcraig@gmail.com>"]
categories = ["development-tools::debugging", "development-tools::profiling", "parser-implementations"]
description = "A blazing fast DWARF debugging format parser."
documentation = "https://docs.rs/gimli"
keywords = ["DWARF", "debug", "ELF", "eh_frame"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/gimli-rs/gimli"
version = "0.15.0"

[badges]
travis-ci = { repository = "gimli-rs/gimli" }
coveralls = { repository = "gimli-rs/gimli" }

[dependencies]
arrayvec = "0.4.6"
byteorder = "1"
fallible-iterator = "0.1.2"

[dev-dependencies]
getopts = "0.2"
memmap = "0.6"
object = "0.6"
test-assembler = "0.1.3"

[features]
nightly = []
